### ISSUE TITLE
Use react-lifecycles-compat with hoc

### ISSUE THREAD

**Issue by pradel** [reactjs/react-lifecycles-compat#19]
Hi!

Looks like we currently we can't use `react-lifecycles-compat` with hoc that are still using the deprecated lifecycles. I am using `react-lifecycles-compat` in my project, the component is working fine if I import it directly, but when I try to render the hoc (tested with jss) I get this warning:

```
Jss(Modal) uses getDerivedStateFromProps() but also contains the following legacy lifecycles:
  componentWillMount
  componentWillReceiveProps
  componentWillUpdate
```

```javascript
import injectSheet from 'react-jss';

// My class that use polyfill

export default injectSheet(styles)(MyClass);
```

Thanks!

**Comment by bvaughn** [comment]
> Looks like we currently we can't use `react-lifecycles-compat` with hoc that are still using the deprecated lifecycles.

This is by design. The full error that's thrown should be:

```
Unsafe legacy lifecycles will not be called for components using new component APIs.

Jss(Modal) uses getDerivedStateFromProps() but also contains the following legacy lifecycles:
  componentWillMount
  componentWillReceiveProps
  componentWillUpdate

The above lifecycles should be removed. Learn more about this warning here:
https://fb.me/react-async-component-lifecycle-hooks
```

In order to support the polyfill- (which relies on using older, deprecated React lifecycles)- we had to make the decision that components can't contain both new and old lifecycles. Otherwise, React 16.3 would end up invoking the new lifecycles twice.

Does this make sense?

**Comment by pradel** [comment]
Of course make sense! But does that mean that we will have to wait that all the hoc libraries that we are using update their code to use `react-lifecycles-compat` (eg jss, recompose ..) ?

**Comment by bvaughn** [comment]
You can use third party components that have been polyfilled with `react-lifecycles-compat` along side of components of your own that use the old API lifecycles. This is fine. You just can't mix old and new lifecycles _within the same component_.

**Comment by pradel** [comment]
Okay after some debugging looks like my component `getDerivedStateFromProps` is called properly, the `react-jss` old lifecycle is just not called (which make senses), I will have to wait for them to use `react-lifecycles-compat` in order to be able to use it.
Thanks for your help :)

**Comment by bvaughn** [comment]
Happy to help 😄
