### ISSUE TITLE
Failed to compile with Create-react-app.

### ISSUE THREAD

**Issue by saostad** [reactjs/react-lifecycles-compat#20]
Failed to compile with Create-react-app.

I am using Version 2.0.1 of react-lifecycles-compat

> Creating an optimized production build...
> Failed to compile.
> 
> Failed to minify the code from this file:
> 
>         ./node_modules/react-lifecycles-compat/react-lifecycles-compat.es.js:64

**Comment by bvaughn** [comment]
There was a problem with version 2.0.1 that was fixed already in the 3.x release, but I've just published 2.0.2 with the fix as well. Cheers!

**Comment by saostad** [comment]
Thanks
