### ISSUE TITLE
 Package is not published pre-compiled

### ISSUE THREAD

**Issue by AbiriAmir** [reactjs/react-lifecycles-compat#22]
This package is not published pre-compiled. So create-react-app can not build this package with this error:

> Failed to minify the code from this file

Please refer to this link:
[https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify](link)

Thank you

**Comment by bvaughn** [comment]
I'm not sure what you're saying. The link you've provided does not work. Please provide the following info:
* What version of `react-lifecycles-compat` are you using.
* What's the full error message (including line number).

I just tested the latest version of all 3 major versions of `react-lifecycles-compat` (1.1.4, 2.0.2, and 3.0.2) with `create-react-app` and they all seemed to work correctly.

**Comment by ulisesbocchio** [comment]
distributions has this:
```js
  let foundWillMountName = null;
  let foundWillReceivePropsName = null;
  let foundWillUpdateName = null;
```
in files: `react-lifecycles-compat.es.js` and `react-lifecycles-compat.cjs`
UglifyJS chokes at the `let` statement.

**Comment by bvaughn** [comment]
If you've installed the latests minor release of 1, 2, or 3 there should be no unsupported keywords like let. (This is why I asked for the specific version, and clarified the ones I tested with.)

I will re-open this issue if more info is provided- but as it stands, my suggestion is to install the latest major release. 😄

**Comment by ulisesbocchio** [comment]
Yeah, I’ve got the latest but I guess there are some rect libraries out there still pointing to the corrupt ones. Temporary solution is to send react-lifecycles-compact through Babel on the webpack config.

**Comment by bvaughn** [comment]
Gotcha. You might also try using the NPM/yarn resolution block to ensure the latest one is snagged.
