### ISSUE TITLE
support UNSAFE_componentWillUnmount

### ISSUE THREAD

**Issue by afc163** [reactjs/react-lifecycles-compat#47]

**Comment by bvaughn** [comment]
There is no such lifecycle. Despite having "will" in its name, `componentWillUnmount` is a commit phase lifecycle meant for cleaning up (e.g. removing event listeners). It's not "unsafe". :smile:

Read about side effects here if you're curious:
https://reactjs.org/docs/strict-mode.html#detecting-unexpected-side-effects

**Comment by afc163** [comment]
Then the usage of react-slick is wrong, thx for Clarifying!

https://github.com/akiran/react-slick/blob/97988e897750e1d8f7b10a86b655f50d75d38298/src/slider.js#L70
https://github.com/akiran/react-slick/blob/97988e897750e1d8f7b10a86b655f50d75d38298/src/slider.js#L70

**Comment by bvaughn** [comment]
cc @akiran https://github.com/akiran/react-slick/issues/1616

**Comment by afc163** [comment]
Fixed in https://github.com/akiran/react-slick/pull/1615
