### ISSUE TITLE
Use named export and add ES module to dist

### ISSUE THREAD

**Issue by bvaughn** [reactjs/react-lifecycles-compat#8]
CJS modules can cause tree shaking problems for other packages that use them. It would be nice to provide an ES module version of this project (which should be as easy as uncommenting [this line](https://github.com/reactjs/react-lifecycles-compat/blob/6ef725e035cb470c8a8d0f6523055ce4dabb0b69/rollup.config.js#L27) and adding a new entry to [the "files" array](https://github.com/reactjs/react-lifecycles-compat/blob/6ef725e035cb470c8a8d0f6523055ce4dabb0b69/package.json#L17-L21).

Unfortunately we can't do that without a breaking change, since the current CJS bundle uses an unnamed/default export which we can't mirror with an ES module (without [causing problems](https://github.com/reactjs/react-lifecycles-compat/issues/7) when required).

I think the most straight forward solution is to use a named export in the next major:
```js
import {polyfill} from 'react-lifecycles-compat';

// or...

const {polyfill} = require('react-lifecycles-compat');
```

We could add a deprecation warning to the default export only and do one final 1.x release before making this change, to follow a similar upgrade strategy as React uses.

**Comment by bvaughn** [comment]
cc @Andarist ~ 2.0 has been released.

**Comment by Andarist** [comment]
😍 super cool!
